name: Build ImmortalWrt for RAX3000M NAND (OpenWrt 24.10)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
        g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
        libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
        libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
        ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
        python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
        upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

    - name: Clone ImmortalWrt
      run: |
        git clone -b openwrt-24.10 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
        cd immortalwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom config
      run: |
        cp configs/rax3000m-nand.config immortalwrt/.config
        cd immortalwrt
        make defconfig

    - name: Build firmware
      run: |
        cd immortalwrt
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: immortalwrt/bin/targets/mediatek/filogic/
