name: Build ImmortalWrt for RAX3000M NAND

on:
  push:
    branches:
      - openwrt-24.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: openwrt-24.10

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
        g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
        libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
        libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
        ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
        python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
        upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

    - name: Run diy-part1.sh
      run: ./scripts/diy-part1.sh

    - name: Update feeds
      run: ./scripts/feeds update -a

    - name: Install feeds
      run: ./scripts/feeds install -a

    - name: Apply custom config
      run: |
        cp IMWRT.config .config
        make defconfig

    - name: Run diy-part2.sh
      run: ./scripts/diy-part2.sh

    - name: Build firmware
      run: make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-firmware
        path: bin/targets/mediatek/filogic/
