name: check-update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00（北京时间 08:00）

permissions:
  contents: write

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  TZ: Asia/Shanghai

jobs:
  check-update:
    runs-on: ubuntu-22.04
    outputs:
      has_update: ${{ steps.check.outputs.has_update }}
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 克隆源码
      run: git clone $REPO_URL -b $REPO_BRANCH openwrt --depth 1

    - name: 检查源码更新
      id: check
      working-directory: ./openwrt
      run: |
        git fetch origin $REPO_BRANCH
        LOCAL_COMMIT=$(git rev-parse HEAD)
        REMOTE_COMMIT=$(git rev-parse origin/$REPO_BRANCH)
        if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
          echo "has_update=true" >> $GITHUB_OUTPUT
        else
          echo "has_update=false" >> $GITHUB_OUTPUT
        fi

  build:
    needs: check-update
    if: needs.check-update.outputs.has_update == 'true'
    runs-on: ubuntu-22.04
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 初始化环境
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y build-essential git libncurses5-dev zlib1g-dev gawk unzip python3 wget
        sudo timedatectl set-timezone "$TZ"

    - name: 克隆源码
      run: git clone $REPO_URL -b $REPO_BRANCH openwrt --depth 1

    - name: 更新并安装 Feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a || {
          echo "src-git packages https://git.openwrt.org/feed/packages.git^v24.10.0" > feeds.conf.default
          ./scripts/feeds update -a
        }
        ./scripts/feeds install -a

    - name: 配置目标设备
      working-directory: ./openwrt
      run: |
        echo "CONFIG_TARGET_mediatek_mt7981=y" > .config
        echo "CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_cmcc_rax3000m-usboffload=y" >> .config
        make defconfig

    - name: 编译固件
      working-directory: ./openwrt
      run: |
        make download -j8
        make -j$(nproc) || make -j1 V=s
        [ -d "bin/targets/mediatek/mt7981" ] || { echo "编译失败"; exit 1; }

    - name: 上传固件
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "immortalwrt-24.10-cmcc_rax3000m-usboffload-${{ github.run_id }}"
        files: openwrt/bin/targets/mediatek/mt7981/*
