name: Cleanup All Workflow Runs

on:
  workflow_dispatch:
    inputs:
      retention_days:
        description: 'Number of days to retain workflow runs'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '7'
          - '14'
          - '30'
          - '90'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all workflows
        id: list-workflows
        run: |
          workflows=$(gh workflow list --all --json id --jq '.[].id' | jq -r '.' | tr '\n' ' ')
          echo "workflows=$workflows" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old workflow runs
        run: |
          for workflow_id in ${{ steps.list-workflows.outputs.workflows }}; do
            echo "Cleaning up workflow ID: $workflow_id"
            gh api -X DELETE \
              -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?exclude_pull_requests=true&created:<$(date -d "-${{ github.event.inputs.retention_days }} days" -Iseconds)" || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
