- name: Get list of workflows
  id: list-workflows
  run: |
    gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/workflows > workflows.json
    echo "API Response:"
    cat workflows.json
    workflow_ids=$(jq '.workflows[].id' workflows.json)
    if [ -z "$workflow_ids" ]; then
        echo "No workflow IDs found. Please check the API response."
        exit 1
    fi
    echo "workflow_ids=$workflow_ids" >> $GITHUB_OUTPUT
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
