name: Clean Old Workflow Runs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  clean-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          current_time=$(date -u +%s)
          two_hours_ago=$((current_time - 7200))
          echo "Current time: $current_time"
          echo "Two hours ago: $two_hours_ago"

          page=1
          while true; do
            echo "Fetching page $page"
            runs=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO/actions/runs?per_page=100&page=$page")
            if [ -z "$(echo "$runs" | jq '.workflow_runs[]')" ]; then
              echo "No more runs to process"
              break
            fi
            echo "$runs" | jq '.workflow_runs[] | {id: .id, created_at: .created_at}'
            run_ids=$(echo "$runs" | jq -r --argjson threshold "$two_hours_ago" \
              '.workflow_runs[] | select((.created_at | sub("\\.[0-9]+Z$"; "Z") | fromdateiso8601) < $threshold) | .id')
            for run_id in $run_ids; do
              echo "Deleting run ID: $run_id"
              response=$(curl -s -w "%{http_code}" -X DELETE \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id")
              echo "Delete response code for run $run_id: $response"
            done
            page=$((page + 1))
          done
