name: 清理所有工作流运行

on:
  workflow_dispatch:
    inputs:
      retention_days:
        description: '保留工作流运行的天数'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '7'
          - '14'
          - '30'
          - '90'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取所有工作流
        id: list-workflows
        run: |
          workflows=$(gh workflow list --all --json id --jq '.[].id' | jq -r '.' | tr '\n' ' ')
          echo "workflows=$workflows" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 删除所有工作流的旧运行
        run: |
          for workflow_id in ${{ steps.list-workflows.outputs.workflows }}; do
            echo "正在清理工作流 ID: $workflow_id"
            gh api -X DELETE \
              -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?exclude_pull_requests=true&created:<$(date -d "-${{ github.event.inputs.retention_days }} days" -Iseconds)" || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
