name: IMwrt-23.05

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_model:
        description: '选择目标设备型号'
        type: choice
        required: true
        options:
          - abt_asr3000
          - cetron_ct3003
          - cmcc_a10
          - cmcc_rax3000m
          - cmcc_rax3000m-emmc
          - cmcc_rax3000m-emmc-usboffload
          - cmcc_rax3000m-usboffload
          - cmcc_rax3000me
          - cmcc_xr30
          - cmcc_xr30-emmc
      enable_5g_25db:
        description: '启用 5G 25dB 修改'
        type: boolean
        required: true
        default: true
      upload_bin_dir:
        description: '上传 bin 目录'
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 7 * * 5'  # 每周五 UTC 时间 07:00 运行（北京时间 15:00）

permissions:
  contents: write
  actions: write

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 2305.config
  DIY_P1_SH: scripts/diy-part1.sh
  DIY_P2_SH: scripts/diy-part2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
  WEBDAV_PATH: WRT23.05  # New: Specify WebDAV folder for 23.05

jobs:
  check-source-updates:
    runs-on: ubuntu-22.04
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check source repository updates
        id: check
        run: |
          LATEST_SHA=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/padavanonly/immortalwrt-mt798x-24.10/commits/$REPO_BRANCH" | jq -r '.sha')
          LAST_CHECKED_FILE="last_checked_sha.txt"
          LAST_CHECKED_SHA=$(cat "$LAST_CHECKED_FILE" 2>/dev/null || echo "")
          if [ "$LATEST_SHA" != "$LAST_CHECKED_SHA" ]; then
            echo "Source repository updated. Latest SHA: $LATEST_SHA, Last checked: $LAST_CHECKED_SHA"
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "$LATEST_SHA" > "$LAST_CHECKED_FILE"
          else
            echo "No updates in source repository, skipping build."
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload last checked SHA
        if: steps.check.outputs.should_build == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-checked-sha
          path: last_checked_sha.txt

  build:
    needs: check-source-updates
    if: github.event_name == 'workflow_dispatch' || (needs.check-source-updates.outputs.should_build == 'true' && github.event_name != 'workflow_dispatch')
    runs-on: ubuntu-22.04
    name: Build ${{ matrix.device_model }}
    strategy:
      matrix:
        device_model: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.device_model && fromJSON(format('["{0}"]', github.event.inputs.device_model)) || fromJSON('["abt_asr3000", "cetron_ct3003", "cmcc_a10", "cmcc_rax3000m", "cmcc_rax3000m-emmc", "cmcc_rax3000m-emmc-usboffload", "cmcc_rax3000m-usboffload", "cmcc_rax3000me", "cmcc_xr30", "cmcc_xr30-emmc"]') }}
    steps:
      - name: Debug information
        run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Device model: ${{ matrix.device_model }}"
          echo "5G 25dB: ${{ github.event.inputs.enable_5g_25db }}"
          echo "Upload bin dir: ${{ github.event.inputs.upload_bin_dir }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check disk space
        run: |
          MIN_SPACE=10
          AVAILABLE=$(df -BG . | tail -1 | awk '{print $4}' | grep -o '[0-9]\+')
          if [ "$AVAILABLE" -lt "$MIN_SPACE" ]; then
            echo "Error: Insufficient disk space, available: ${AVAILABLE}G, required: ${MIN_SPACE}G"
            exit 1
          fi
          echo "Available disk space: ${AVAILABLE}G"

      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
            git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
            libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
            libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
            python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
            uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zip
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Cache build intermediates
        uses: actions/cache@v4
        with:
          path: |
            /workdir/openwrt/dl
            /workdir/openwrt/build_dir
            /workdir/openwrt/staging_dir
          key: ${{ runner.os }}-build-${{ matrix.device_model }}-${{ hashFiles('openwrt/.config', 'feeds.conf.default') }}
          restore-keys: ${{ runner.os }}-build-${{ matrix.device_model }}-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ matrix.device_model }}-${{ hashFiles('openwrt/.config', 'feeds.conf.default') }}
          restore-keys: ${{ runner.os }}-ccache-${{ matrix.device_model }}-

      - name: Configure ccache
        run: |
          echo "export PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
          echo "export CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          ccache -M 5G

      - name: Cache Feeds
        uses: actions/cache@v4
        with:
          path: /workdir/openwrt/feeds
          key: ${{ runner.os }}-feeds-${{ hashFiles('feeds.conf.default') }}
          restore-keys: ${{ runner.os }}-feeds-

      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          rm -rf /workdir/openwrt
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Check Feeds configuration changes
        id: check_feeds
        run: |
          if [ -f openwrt/feeds.conf.default ] && cmp -s openwrt/feeds.conf.default $FEEDS_CONF; then
            echo "feeds_unchanged=true" >> $GITHUB_OUTPUT
          else
            echo "feeds_unchanged=false" >> $GITHUB_OUTPUT
          fi

      - name: Load Feeds
        timeout-minutes: 10
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: Update Feeds
        if: steps.check_feeds.outputs.feeds_unchanged == 'false'
        timeout-minutes: 20
        run: |
          cd openwrt
          ./scripts/feeds update -a || { echo "Failed to update Feeds"; exit 1; }
          ./scripts/feeds install -a || { echo "Failed to install Feeds"; exit 1; }

      - name: Load configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          echo "CONFIG_TARGET_mediatek_mt7981_DEVICE_${{ matrix.device_model }}=y" >> openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
          make defconfig

      - name: Download packages
        timeout-minutes: 30
        run: |
          cd openwrt
          make download -j8 || { echo "Failed to download packages"; exit 1; }
          find dl -size -1024c -exec rm -f {} \;

      - name: Modify 5G 25dB
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.enable_5g_25db == 'true'
        working-directory: ./openwrt
        run: |
          EEPROM_FILE=package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom/MT7981_iPAiLNA_EEPROM.bin
          EXPECTED_CONTENT=$(printf '\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B')
          if [ ! -f "$EEPROM_FILE" ]; then
            echo "EEPROM file not found, creating new file"
            mkdir -p "$(dirname "$EEPROM_FILE")"
            touch "$EEPROM_FILE"
          fi
          CURRENT_CONTENT=$(dd if="$EEPROM_FILE" bs=1 skip=$((0x445)) count=20 2>/dev/null || echo "")
          if [ "$CURRENT_CONTENT" != "$EXPECTED_CONTENT" ]; then
            printf '\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B' | dd of="$EEPROM_FILE" bs=1 seek=$((0x445)) conv=notrunc
            echo "EEPROM file updated"
          else
            echo "EEPROM file does not need modification"
          fi

      - name: Check source changes
        id: check_source
        run: |
          cd openwrt
          if git diff --name-only HEAD^ HEAD | grep -E '^(package/|target/)'; then
            echo "source_changed=true" >> $GITHUB_OUTPUT
          else
            echo "source_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Compile firmware
        id: compile
        timeout-minutes: 120
        run: |
          cd openwrt
          if [ "${{ steps.check_source.outputs.source_changed }}" == "false" ]; then
            echo "No source changes, performing incremental build"
            make -j$(nproc) CCACHE=1 package/index
            make -j1 target/install
          else
            echo "Source changes detected, performing full build"
            make -j$(nproc) CCACHE=1 || make -j1 V=s CCACHE=1
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          echo "DEVICE_NAME=_${{ matrix.device_model }}" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Upload compile logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compile-log-${{ matrix.device_model }}
          path: |
            openwrt/build_dir/**/*.log
            openwrt/logs/*.log
            openwrt/*.log

      - name: Extract firmware version
        id: version
        if: steps.compile.outputs.status == 'success'
        run: |
          cd openwrt
          VERSION_FILE=$(find bin/targets/*/*/ -type f -name "openwrt_version" 2>/dev/null | head -n 1)
          if [ -n "$VERSION_FILE" ] && [ -f "$VERSION_FILE" ]; then
            VERSION=$(cat "$VERSION_FILE")
            echo "Extracted version from $VERSION_FILE: $VERSION"
          else
            VERSION_FILE=$(find staging_dir/target-*/root-*/etc/ -type f -name "openwrt_version" 2>/dev/null | head -n 1)
            if [ -n "$VERSION_FILE" ] && [ -f "$VERSION_FILE" ]; then
              VERSION=$(cat "$VERSION_FILE")
              echo "Extracted version from $VERSION_FILE: $VERSION"
            else
              VERSION="23.05-SNAPSHOT-r$(git rev-list --count origin/$REPO_BRANCH)-$(git rev-parse --short origin/$REPO_BRANCH)"
              echo "No openwrt_version found, using source version: $VERSION"
            fi
          fi
          SAFE_VERSION=$(echo "$VERSION" | grep -o 'r[0-9]\+' || echo "r0000")
          [ -z "$SAFE_VERSION" ] && SAFE_VERSION="r0000"
          echo "Extracted version number: $SAFE_VERSION"
          echo "FIRMWARE_VERSION=$SAFE_VERSION" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Check disk
        if: always()
        run: df -hT

      - name: Upload bin directory
        uses: actions/upload-artifact@v4
        if: steps.compile.outputs.status == 'success' && github.event_name == 'workflow_dispatch' && github.event.inputs.upload_bin_dir == 'true'
        with:
          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin

      - name: Organize firmware and standardize filenames
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          for file in *sysupgrade.bin *factory.bin; do
            if [ -f "$file" ]; then
              TYPE=$(echo "$file" | grep -o "sysupgrade\|factory")
              NEW_NAME="${{ matrix.device_model }}_25dB-${{ (github.event_name != 'workflow_dispatch' || github.event.inputs.enable_5g_25db == 'true') && 'on' || 'off' }}_${{ env.FIRMWARE_VERSION }}_${TYPE}.bin"
              mv "$file" "$NEW_NAME"
            fi
          done
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Generate tag and release description
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success'
        run: |
          echo "RELEASE_TAG=ImmortalWrt-23.05-${{ matrix.device_model }}-${{ env.FIRMWARE_VERSION }}" >> $GITHUB_OUTPUT
          cat << EOF > release.txt
          **Firmware Version**: ImmortalWrt ${{ env.FIRMWARE_VERSION }}  
          **Device**: ${{ matrix.device_model }}  
          **Build Time**: $(date +"%Y-%m-%d %H:%M %Z")  
          **High Power Mode**: ${{ (github.event_name != 'workflow_dispatch' || github.event.inputs.enable_5g_25db == 'true') && 'Enabled' || 'Disabled' }}  
          EOF
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Publish firmware
        uses: softprops/action-gh-release@v2
        if: steps.tag.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.RELEASE_TAG }}
          body_path: release.txt
          files: |
            ${{ env.FIRMWARE }}/*sysupgrade.bin
            ${{ env.FIRMWARE }}/*factory.bin
          overwrite: true

      - name: Check WebDAV credentials
        if: steps.compile.outputs.status == 'success' && env.WEBDAV_URL && env.WEBDAV_USERNAME && env.WEBDAV_PASSWORD
        run: |
          if [ -z "$WEBDAV_URL" ] || [ -z "$WEBDAV_USERNAME" ] || [ -z "$WEBDAV_PASSWORD" ]; then
            echo "Error: Missing WebDAV credentials (WEBDAV_URL, WEBDAV_USERNAME, WEBDAV_PASSWORD)"
            exit 1
          fi
          echo "WebDAV credentials verified"

      - name: Upload to WebDAV
        if: steps.compile.outputs.status == 'success' && env.WEBDAV_URL && env.WEBDAV_USERNAME && env.WEBDAV_PASSWORD
        run: |
          SYSUPGRADE_FILES=$(find openwrt/bin/targets -type f -name "*sysupgrade.bin")
          if [ -z "$SYSUPGRADE_FILES" ]; then
            echo "No sysupgrade.bin files found, skipping upload"
            exit 0
          fi
          for FILE in $SYSUPGRADE_FILES; do
            echo "Uploading file: $FILE"
            curl --retry 3 --retry-delay 5 -u "${{ env.WEBDAV_USERNAME }}:${{ env.WEBDAV_PASSWORD }}" \
                 -T "$FILE" \
                 "${{ env.WEBDAV_URL }}/${{ env.WEBDAV_PATH }}/$(basename "$FILE")" || { echo "Upload failed: $(basename "$FILE")"; exit 1; }
            echo "Uploaded: $(basename "$FILE")"
          done
          echo "All files uploaded successfully"

      - name: Clean up old Releases
        if: steps.tag.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES=$(gh release list --repo ${{ github.repository }} --limit 100 --json name --jq '.[] | select(.name | test("ImmortalWrt-23.05-${{ matrix.device_model }}")) | .name' | tail -n +21)
          if [ -n "$RELEASES" ]; then
            for RELEASE in $RELEASES; do
              gh release delete "$RELEASE" --yes || { echo "Failed to delete Release $RELEASE"; exit 1; }
            done
          else
            echo "No old Releases to clean up"
          fi

      - name: Clean up old workflow runs
        if: steps.tag.outputs.status == 'success'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 20
