name: ImmortalWrt MT798x Builder

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间6点（UTC 22:00）
  workflow_dispatch:
  repository_dispatch:

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  CONFIG_FILE: 2410.config
  DIY_P1_SH: scripts/diy-part1.sh
  DIY_P2_SH: scripts/diy-part2.sh
  EEPROM_FILE: eeprom/MT7981_iPAiLNA_EEPROM.bin
  TARGET_EEPROM_PATH: package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom/MT7981_iPAiLNA_EEPROM.bin
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  ENABLE_5G_25DB: ${{ github.event_name == 'workflow_dispatch' && inputs.enable_5g_25db || 'true' }}
  DEVICE_MODEL: ${{ github.event_name == 'workflow_dispatch' && inputs.device_model || 'cmcc_rax3000m-emmc-usboffload' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        device: 
          - cmcc_rax3000m-emmc-usboffload
          - cmcc_rax3000m-usboffload
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Load custom feeds
        run: |
          chmod +x $DIY_P1_SH || echo "Warning: $DIY_P1_SH not found"
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH || echo "Warning: $DIY_P1_SH failed"

      - name: Update and install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply 5G 25dB EEPROM if enabled
        if: env.ENABLE_5G_25DB == 'true'
        run: |
          cd openwrt
          mkdir -p $(dirname $TARGET_EEPROM_PATH)
          cp $GITHUB_WORKSPACE/$EEPROM_FILE $TARGET_EEPROM_PATH || echo "Error: EEPROM file not found"
          echo "Applied 5G 25dB EEPROM"

      - name: Load custom configuration
        run: |
          if [ -e $CONFIG_FILE ]; then
            cp $GITHUB_WORKSPACE/$CONFIG_FILE openwrt/.config
          else
            echo "Error: $CONFIG_FILE not found in repository"
            exit 1
          fi
          chmod +x $DIY_P2_SH || echo "Warning: $DIY_P2_SH not found"
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH || echo "Warning: $DIY_P2_SH failed"
          echo "CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_${{ matrix.device }}=y" >> .config
          make defconfig
          cat .config > config_dump.txt  # 输出最终配置用于调试

      - name: Download package
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo "Starting compilation for ${{ matrix.device }}"
          make -j$(nproc) || make -j1 V=s 2> compile_error.log
          if [ $? -ne 0 ]; then
            echo "Compilation failed, see compile_error.log"
            cat compile_error.log
            exit 1
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          echo "DEVICE_NAME=_${{ matrix.device }}" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Upload debug logs
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: debug_logs_${{ matrix.device }}
          path: |
            openwrt/.config
            openwrt/compile_error.log

      - name: Organize files
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ImmortalWrt_${{ matrix.device }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}
