name: build-MT7981-24.10

on:
  workflow_dispatch:
    inputs:
      device:
        description: '选择设备型号'
        required: true
        type: choice
        options:
          - abt_asr3000
          - cetron_ct3003
          - cmcc_a10
          - cmcc_rax3000m-emmc-usboffload
          - cmcc_rax3000m-usboffload
          - h3c_nx30pro
          - imou_lc-hx3001
          - jcg_q30
          - konka_komi-a31
          - livinet_zr-3020
          - mt7981-360-t7-108M
          - mt7981-clt-r30b1
          - mt7981-clt-r30b1-112M
          - xiaomi_mi-router-ax3000t
          - xiaomi_mi-router-ax3000t-stock
          - xiaomi_mi-router-wr30u-112m
          - xiaomi_mi-router-wr30u-stock
      enable_5g_25db:
        description: '启用 5G WiFi 25dB 支持'
        default: 'true'
        type: boolean
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间 08:00

permissions:
  contents: write

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 初始化环境
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y build-essential git libncurses5-dev zlib1g-dev gawk unzip python3 wget
        sudo timedatectl set-timezone "$TZ"

    - name: 克隆源码
      run: git clone $REPO_URL -b $REPO_BRANCH openwrt --depth 1

    - name: 更新并安装 Feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a || {
          echo "src-git packages https://git.openwrt.org/feed/packages.git^v24.10.0" > feeds.conf.default
          ./scripts/feeds update -a
        }
        ./scripts/feeds install -a

    - name: 配置目标设备
      working-directory: ./openwrt
      run: |
        echo "CONFIG_TARGET_mediatek_mt7981=y" > .config
        echo "CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_${{ github.event.inputs.device || 'cmcc_rax3000m-usboffload' }}=y" >> .config
        make defconfig

    - name: 应用 5G 25dB 修改（可选）
      if: github.event.inputs.enable_5g_25db == 'true'
      working-directory: ./openwrt
      run: |
        mkdir -p package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom
        printf '\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B\x2B' | dd of=package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom/MT7981_iPAiLNA_EEPROM.bin bs=1 seek=$((0x445)) conv=notrunc

    - name: 编译固件
      working-directory: ./openwrt
      run: |
        make download -j8
        make -j$(nproc) || make -j1 V=s
        [ -d "bin/targets/mediatek/mt7981" ] || { echo "编译失败"; exit 1; }

    - name: 上传固件
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "immortalwrt-24.10-${{ github.event.inputs.device || 'cmcc_rax3000m-usboffload' }}-${{ github.run_id }}"
        files: openwrt/bin/targets/mediatek/mt7981/*
